=== vaxradius/AmbiqSuite-R2.5.1/docs/registers/apollo2/xml_src/internal/xml_devices.dtd
<?xml version="1.0" encoding="iso-8859-2" ?>

<!--
================================================================================
== 
== Filename: xml_devices.dtd
== 
== Description: Document type definition for device definition xml.
== 
================================================================================
==  Each xml file defines the programmable I/O registers within a single device.
==  The base address for devices I/O space comes from a separate xml data base.
== 
================================================================================
==  COPYRIGHT 2003 A6LABS
== 
================================================================================
-->



<!ELEMENT device            (short_description, 
                             bus_type,
                             device_name,
			     io_device_size,
                             ioregisters)>
<!ATTLIST device            file_name CDATA #REQUIRED
                            file_mod_date CDATA #REQUIRED
>
<!ELEMENT short_description (#PCDATA)>
<!ELEMENT bus_type          (#PCDATA)>
<!ELEMENT device_name       (#PCDATA)>
<!ELEMENT io_device_size    (#PCDATA)>
<!ELEMENT ioregisters       (ioreg_index, 
                             ioreg+,
                             ioreg_bigpicture)>
<!ELEMENT ioreg             (ioreg_name,
                             ioreg_offset, 
                             ioreg_intro, 
			     ioreg_encoding, 
			     ioreg_description, 
                             ioreg_no_debug?,
                             ioreg_example?)>
<!ATTLIST ioreg              skip                CDATA #REQUIRED
>
<!ELEMENT ioreg_name        (#PCDATA)>
<!ELEMENT ioreg_offset      (#PCDATA)>
<!ELEMENT ioreg_encoding    (ioreg_bitfield+)>
<!ELEMENT ioreg_bitfield    (
                             ioreg_bf_description,
                             ioreg_bf_enum*)>
<!ATTLIST ioreg_bitfield   name                CDATA #REQUIRED
                           width               CDATA #REQUIRED
                           lsb                 CDATA #REQUIRED
                           reset_value         CDATA #REQUIRED 
                           readwrite           CDATA #REQUIRED 
                           interrupt           CDATA #IMPLIED
                           reserved            CDATA #IMPLIED
                           do_not_autotest     CDATA #IMPLIED
                           empty               CDATA #IMPLIED
                           backdoor            CDATA #IMPLIED
                           bd_set              CDATA #IMPLIED
                           bd_reset            CDATA #IMPLIED
                           softreset           CDATA #IMPLIED
>
<!ELEMENT ioreg_bf_description (#PCDATA)>
<!ELEMENT ioreg_bf_enum (#PCDATA)>
<!ATTLIST ioreg_bf_enum      name                CDATA #REQUIRED
                           value               CDATA #REQUIRED
>
<!ELEMENT ioreg_example     (#PCDATA)>
<!ELEMENT ioreg_no_debug    (#PCDATA)>
<!ATTLIST ioreg_no_debug     skip                CDATA #REQUIRED
>
<!ELEMENT ioreg_description (#PCDATA)>
<!ELEMENT ioreg_intro       (#PCDATA)>
<!ELEMENT ioreg_index       (#PCDATA)>
<!ELEMENT ioreg_bigpicture  (#PCDATA)>

=== vaxradius/AmbiqSuite-R2.5.1/docs/registers/apollo/xml_src/vcomp_regs.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="xml_devices.xsl"?>
<!DOCTYPE device SYSTEM "xml_devices.dtd">
<device file_name="docs/vcomp_regs.xml" file_mod_date="May 29 10:05:02 2014">
  <short_description>Voltage Comparator</short_description>
  <device_name>VCOMP</device_name>
  <instance_base>REG_VCOMP_BASEADDR: 0x4000C000</instance_base>
  <ioregisters>
    <ioreg_index/>
    <ioreg>
    <ioreg_name>VCMP_CFG</ioreg_name>
    <ioreg_offset>0x00000000</ioreg_offset>
    <ioreg_intro>Configuration Register</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="20" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="12" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="16" name="LVLSEL" readwrite="RW" access_macro="REG_VCOMP_VCMP_CFG_LVLSEL_WR" reset_value="0x0" width="4">
        <ioreg_bf_description>"This bitfield selects the voltage level for the negative input to the comparator."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="10" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="6" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="8" name="NSEL" readwrite="RW" access_macro="REG_VCOMP_VCMP_CFG_NSEL_WR" reset_value="0x0" width="2">
        <ioreg_bf_description>"This bitfield selects the negative input to the comparator."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="6" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="PSEL" readwrite="RW" access_macro="REG_VCOMP_VCMP_CFG_PSEL_WR" reset_value="0x0" width="2">
        <ioreg_bf_description>"This bitfield selects the positive input to the comparator."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_STAT</ioreg_name>
    <ioreg_offset>0x00000004</ioreg_offset>
    <ioreg_intro>Status Register</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="30" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="1" name="PWDSTAT" readwrite="RO" access_macro="REG_VCOMP_VCMP_STAT_PWDSTAT_RD" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit indicates the power down state of the voltage comparator."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="CMPOUT" readwrite="RO" access_macro="REG_VCOMP_VCMP_STAT_CMPOUT_RD" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is 1 if the positive input of the comparator is greater than the negative input."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_PWDKEY</ioreg_name>
    <ioreg_offset>0x00000008</ioreg_offset>
    <ioreg_intro>Key Register for Powering Down the Voltage Comparator</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="0" name="VALUE" readwrite="RW" access_macro="REG_VCOMP_VCMP_PWDKEY_VALUE_WR" reset_value="0x0" width="32">
        <ioreg_bf_description>Key value. (0x37 unlocks)
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_IEREN</ioreg_name>
    <ioreg_offset>0x00000200</ioreg_offset>
    <ioreg_intro>Votage Comparator Interrupt registers</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="30" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="1" name="OUTHI" readwrite="RW" access_macro="REG_VCOMP_VCMP_IEREN_OUTHI_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout high interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="OUTLOW" readwrite="RW" access_macro="REG_VCOMP_VCMP_IEREN_OUTLOW_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout low interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_IERSTAT</ioreg_name>
    <ioreg_offset>0x00000204</ioreg_offset>
    <ioreg_intro>Votage Comparator Interrupt registers</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="30" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="1" name="OUTHI" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERSTAT_OUTHI_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout high interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="OUTLOW" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERSTAT_OUTLOW_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout low interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_IERCLR</ioreg_name>
    <ioreg_offset>0x00000208</ioreg_offset>
    <ioreg_intro>Votage Comparator Interrupt registers</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="30" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="1" name="OUTHI" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERCLR_OUTHI_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout high interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="OUTLOW" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERCLR_OUTLOW_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout low interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg>
    <ioreg_name>VCMP_IERSET</ioreg_name>
    <ioreg_offset>0x0000020c</ioreg_offset>
    <ioreg_intro>Votage Comparator Interrupt registers</ioreg_intro>
    <ioreg_encoding>
      <ioreg_bitfield lsb="2" name="RSVD" readwrite="RO" access_macro="N/A" reset_value="0x0" width="30" reserved="reserved">
        <ioreg_bf_description>"This bitfield is reserved for future use."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="1" name="OUTHI" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERSET_OUTHI_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout high interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
      <ioreg_bitfield lsb="0" name="OUTLOW" readwrite="RW" access_macro="REG_VCOMP_VCMP_IERSET_OUTLOW_WR" reset_value="0x0" width="1">
        <ioreg_bf_description>"This bit is the vcompout low interrupt."
        </ioreg_bf_description>
      </ioreg_bitfield>
    </ioreg_encoding>
    <ioreg_description>Needs a description.</ioreg_description>
    <ioreg_example>No example yet!!
    </ioreg_example>
    </ioreg>
    <ioreg_bigpicture/>
  </ioregisters>
</device>
